language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

env:
  global:
   - GH_REF: github.com/la-veilleuse/la-veilleuse.git
   - secure: "DzTtbaPeQQEeTB+pveCxfgZfnM+sdbFfL1slyKXo3SPtuW8kC6CMYkOQ83+inpbjsbCVO3kIsMYRun4+wHRcU+emSxaMLIig0BotlUGWSbKN/H77XDvqywOEMIFtm4b9kNHKsEBro/YnKwieOXngmS+8TlKgWtunS5o7zi4Am09zkjHHnJhxIUa7UFMO+IDMODA5yP0lhksTUkb8ndLiLuXyNZOGccaVOLmO39nRq/hrO/gTIes4EyAalY3vUIBQTBPsvle9F82L3PqolcyF6cBSY5HXsfy9Ir1KvQoM5UibBS/EKp3mImu9xMW/W7koFBJ4WTFLcfYfnw8aTIHogE36+sGFXwOx2Qpru8RP1NnY4+4sEyIKwcZ2v3W+cT+Debx1cZx0PWx7Uip1eqZYykf1/TX64Fox13RjievraI8PCM4w4LXPgLpNJYxMkkBjmfget6pl98MqGp2bvzkLetXUOQnZzz1CkJFMzPR3XCBdhr30cJTKgSdyCUTLgAPUuGKCCzE9NYlrURahJQ33x6tZjTYSzPeXavdc6iE+Mkd06/NgBYMFQNetkWt8wHDalvpzGB+Gl5tbmKk4e5uWYfANWMl14kHt7JQIOIg0LWNCiFAUcwhx0/ncTHkQ+gPR3CirFtI6ZuPR3KJHQxOSa4RDcjNHBhrJzJw+5hkVqds="

script:
 - npm run build

deploy:
  provider: script
  script: npm run deploy
  on:
    branch: master
